apiVersion: v1
kind: Service
metadata:
  name: giant-gorilla
  namespace: app-bar-prd
  labels:
    app: giant-gorilla
    env: prd
spec:
  type: NodePort
  selector:
    app: giant-gorilla
    env: prd
  ports:
      - nodePort: 31001
        protocol: TCP
        port: 8080
