apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-app4
  namespace: argocd
spec:
  project: london
  source:
    repoURL: https://github.com/matholbrook/argo-app4
    targetRevision: HEAD # or a specific branch/tag
    path: app/
  destination:
    server: https://kubernetes.default.svc # Use appropriate server URL
    namespace: app-bar-prd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
